async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 20
      queue_capacity: 99999
      keep_alive_seconds: 20000
      await_termination: 24h
      wait_for_tasks_to_complete_on_shutdown: false
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.7.211:1521:orcl
    username: msth
    password: 1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
logging:
  config: classpath:spring-logback.xml